package view;


/**
 *
 * @author bhlb
 */
public class AdminPanel extends PanelModel {

    /** Creates new form AdminPanel */
    public AdminPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 630));
        setLayout(null);
    }// </editor-fold>


    // Variables declaration - do not modify
    // End of variables declaration

}
