package view;
import net.ServerThread;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on 2011-11-23, 23:06:32
 */

//package view;

/**
 *
 * @author bhlb
 */
public class MainView extends javax.swing.JFrame implements ShowMainViewInterface, ShowAdminMainViewInterface{
//	private MainViewController mainViewController;
    /** Creates new form MainView */
	private ButtonsPanel buttonsPanel;
	private LoginPanel loginPanel;
	private ManageItemPanel manageItemPanel;
	private ItemDiscountPanel itemDiscountPanel;
	private ItemGiftPanel itemGiftPanel;
	private SaleDiscountPanel saleDiscountPanel;
	private SaleGiftPanel saleGiftPanel;
	private AdminPanel adminPanel;
	private Thread server;
    public MainView() {
//    	mainViewController = new MainViewController(this);
    	buttonsPanel = new ButtonsPanel();
    	manageItemPanel = new ManageItemPanel();
		itemDiscountPanel = new ItemDiscountPanel();
		loginPanel = new LoginPanel(this,this);
		itemGiftPanel = new ItemGiftPanel();
		saleDiscountPanel = new SaleDiscountPanel();
		saleGiftPanel = new SaleGiftPanel();
		adminPanel = new AdminPanel();
		server = new ServerThread();
        initComponents();
    }
    
    private void showLoginView(){
    	getContentPane().add(loginPanel);
		pack();
    }
    public void showMainView() {
		// TODO Auto-generated method stub
//    	server.startServer();
    	showManageItemPanel();

	}
    private void showManageItemPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(manageItemPanel);
    	pack();
    	repaint();
    }
    private void showItemSalesPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(itemDiscountPanel);
    	pack();
    	repaint();
    }
    private void showTotalSalesPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(saleDiscountPanel);
    	pack();
    	repaint();
    	
    	
    }
    
    private void showItemGiftPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(itemGiftPanel);
    	pack();
    	repaint();
    }
    private void showTotalGiftPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(saleGiftPanel);
    	pack();
    	repaint();
    	
    }
    

    public void showAnalyPanel(){
    	
    }
    public void showAdminPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(adminPanel);
    	pack();
    	repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());
//        getContentPane().add(manageItemPanel2);
//        mainViewController.showLoginView();
        showLoginView();

        pack();
    }// </editor-fold>

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    	Skin.set();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
        
    }
    public class ButtonsPanel extends javax.swing.JPanel {

//    	private MainViewController mainViewController;
        /** Creates new form ButtonsPanel */
        public ButtonsPanel() {
            initComponents();
        }

        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {
	
	        btn_itemChange = new javax.swing.JButton();
	        btn_itemSales = new javax.swing.JButton();
	        btn_itemGift = new javax.swing.JButton();
	        btn_analy = new javax.swing.JButton();
	        btn_totalSales = new javax.swing.JButton();
	        btn_total_Gift = new javax.swing.JButton();
	
	        setFont(new java.awt.Font("微软雅黑", 0, 18));
	        setPreferredSize(new java.awt.Dimension(150, 600));
	        setLayout(null);
	
	        btn_itemChange.setFont(getFont());
	        btn_itemChange.setText("商品调整");
	        btn_itemChange.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_itemChangeActionPerformed(evt);
	            }
	        });
	        add(btn_itemChange);
	        btn_itemChange.setBounds(10, 30, 120, 40);
	
	        btn_itemSales.setFont(getFont());
	        btn_itemSales.setText("商品特价");
	        btn_itemSales.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_itemSalesActionPerformed(evt);
	            }
	        });
	        add(btn_itemSales);
	        btn_itemSales.setBounds(10, 90, 120, 40);
	
	        btn_itemGift.setFont(getFont());
	        btn_itemGift.setText("商品赠送");
	        btn_itemGift.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_itemGiftActionPerformed(evt);
	            }
	        });
	        add(btn_itemGift);
	        btn_itemGift.setBounds(10, 220, 120, 40);
	
	        btn_analy.setFont(getFont());
	        btn_analy.setText("库存分析");
	        btn_analy.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_analyActionPerformed(evt);
	            }
	        });
	        add(btn_analy);
	        btn_analy.setBounds(10, 360, 120, 40);
	
	        btn_totalSales.setFont(getFont());
	        btn_totalSales.setText("总额特价");
	        btn_totalSales.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_totalSalesActionPerformed(evt);
	            }
	        });
	        add(btn_totalSales);
	        btn_totalSales.setBounds(10, 150, 120, 40);
	
	        btn_total_Gift.setFont(getFont());
	        btn_total_Gift.setText("总额赠送");
	        btn_total_Gift.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_total_GiftActionPerformed(evt);
	            }
	        });
	        add(btn_total_Gift);
	        btn_total_Gift.setBounds(10, 290, 120, 40);
	    }// </editor-fold>
	
	    private void btn_analyActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	showAnalyPanel();
	    }                                        
	
	    private void btn_itemChangeActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	showManageItemPanel();
	    }                                        
	
	    private void btn_itemSalesActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	showItemSalesPanel();
	    }                                        
	
	    private void btn_itemGiftActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	showItemGiftPanel();
	    }                                        
	
	    private void btn_totalSalesActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    	showTotalSalesPanel();
	    }
	
	    private void btn_total_GiftActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    	showTotalGiftPanel();
	    }
	
	
	        // Variables declaration - do not modify
	    private javax.swing.JButton btn_analy;
	    private javax.swing.JButton btn_itemChange;
	    private javax.swing.JButton btn_itemGift;
	    private javax.swing.JButton btn_itemSales;
	    private javax.swing.JButton btn_totalSales;
	    private javax.swing.JButton btn_total_Gift;
	        // End of variables declaration
	
	    }

	

    // Variables declaration - do not modify
    // End of variables declaration

}
