/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TotalGiftPanel.java
 *
 * Created on 2011-11-26, 22:46:08
 */

package view;

import java.util.ArrayList;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import logic.controller.SaleGiftController;
import logic.interfaces.SaleGiftInterface;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author bhlb
 */
public class SaleGiftPanel extends javax.swing.JPanel {

    /** Creates new form TotalGiftPanel */
    public SaleGiftPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        removeAll();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        text_price = new javax.swing.JTextField();
        text_itemID = new javax.swing.JTextField();
        text_number = new javax.swing.JTextField();
        text_start = new javax.swing.JTextField();
        text_end = new javax.swing.JTextField();
        btn_price = new javax.swing.JButton();
        btn_itemID = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text_IDRemove = new javax.swing.JTextField();

        setFont(new java.awt.Font("微软雅黑", 0, 18));
        setPreferredSize(new java.awt.Dimension(850, 630));
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "总额额度", "赠品标识", "赠品描述", "赠品价格", "赠送数量", "开始日期", "结束日期"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(5, 60, 600, 520);

        jButton1.setFont(getFont());
        jButton1.setText("移除");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(730, 550, 80, 30);

        jLabel1.setFont(getFont());
        jLabel1.setText("结束日期");
        add(jLabel1);
        jLabel1.setBounds(620, 400, 80, 30);

        jLabel2.setFont(getFont());
        jLabel2.setText("总额额度");
        add(jLabel2);
        jLabel2.setBounds(620, 170, 80, 30);

        jLabel3.setFont(getFont());
        jLabel3.setText("\u4fc3\u9500\u6807\u8bc6");
        add(jLabel3);
        jLabel3.setBounds(620, 500, 80, 30);

        jLabel4.setFont(getFont());
        jLabel4.setText("\u8d60\u54c1\u4fe1\u606f");
        add(jLabel4);
        jLabel4.setBounds(620, 20, 80, 30);

        jLabel5.setFont(getFont());
        jLabel5.setText("赠送数量");
        add(jLabel5);
        jLabel5.setBounds(620, 300, 80, 30);

        jLabel6.setFont(getFont());
        jLabel6.setText("开始日期");
        add(jLabel6);
        jLabel6.setBounds(620, 350, 80, 30);

        btn_add.setFont(getFont());
        btn_add.setText("增加");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        add(btn_add);
        btn_add.setBounds(620, 450, 80, 30);
        add(text_price);
        text_price.setBounds(620, 210, 80, 30);
        add(text_itemID);
        text_itemID.setBounds(730, 210, 80, 30);

        add(text_number);
        text_number.setBounds(730, 300, 80, 30);
        add(text_start);
        text_start.setBounds(730, 350, 80, 30);
        add(text_end);
        text_end.setBounds(730, 400, 80, 30);
        text_end.setAutoscrolls(false);

        btn_price.setFont(getFont());
        btn_price.setText("确认");
        btn_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_priceActionPerformed(evt);
            }
        });
        add(btn_price);
        btn_price.setBounds(620, 250, 80, 30);

        btn_itemID.setFont(getFont());
        btn_itemID.setText("确认");
        btn_itemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_itemIDActionPerformed(evt);
            }
        });
        add(btn_itemID);
        btn_itemID.setBounds(730, 250, 80, 30);

        btn_cancel.setFont(getFont());
        btn_cancel.setText("取消");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        add(btn_cancel);
        btn_cancel.setBounds(730, 450, 80, 30);

        jLabel7.setFont(getFont());
        jLabel7.setText("\u8d60\u54c1\u6807\u8bc6");
        add(jLabel7);
        jLabel7.setBounds(730, 170, 80, 30);
        add(text_IDRemove);
        text_IDRemove.setBounds(730, 500, 80, 30);
        {
        	text_info = new javax.swing.JTextArea();
        	this.add(text_info);
        	text_info.setColumns(20);
        	text_info.setRows(5);
        	text_info.setBounds(620, 60, 200, 100);
        }
        {
        	jLabel8 = new JLabel();
        	this.add(jLabel8);
        	jLabel8.setText("\u603b\u989d\u8d60\u9001\u5217\u8868");
        	jLabel8.setBounds(10, 20, 120, 30);
        	jLabel8.setFont(new java.awt.Font("微软雅黑",0,18));
        }

        controller=new SaleGiftController();
        controller.start();
        update();
    }// </editor-fold>

    
    public void update(){
		while(jTable1.getModel().getRowCount()!=0){
			((DefaultTableModel) jTable1.getModel()).removeRow(0);
		}
		ArrayList<String> promotions=controller.getPromotionList();
		if(promotions==null){
			return;
		}
		for(int i=0;i<promotions.size();i++){
			//System.out.println(itemListInfo.get(i));
			String item[]=promotions.get(i).split(",");
			((DefaultTableModel) jTable1.getModel()).addRow(item);
		}
    }
    private void btn_priceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.setPrice(text_price.getText());
    	if(!ok){
			JOptionPane.showMessageDialog(null, "输入错误");
			return;
    	}
    	
    }

    private void btn_itemIDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.setGiftID(text_itemID.getText());
    	if(!ok){
			JOptionPane.showMessageDialog(null, "输入错误");
			return;
    	}
    	text_info.setText(controller.getGiftInfo(text_itemID.getText()));
    }

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	initComponents();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.removeGift(text_IDRemove.getText());
    	if(!ok){
    		JOptionPane.showMessageDialog(null, "输入错误");
    	}
    	update();
    }

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.setGift(text_number.getText(), text_start.getText(), text_end.getText());
    	if(!ok){
    		JOptionPane.showMessageDialog(null, "输入错误");
    	}
    	update();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_itemID;
    private javax.swing.JButton btn_price;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private JLabel jLabel8;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_IDRemove;
    private javax.swing.JTextField text_end;
    private javax.swing.JTextArea text_info;
    private javax.swing.JTextField text_itemID;
    private javax.swing.JTextField text_number;
    private javax.swing.JTextField text_price;
    private javax.swing.JTextField text_start;
    private SaleGiftInterface controller;
    // End of variables declaration

}
