/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on 2011-11-23, 23:06:32
 */

package view;

import net.ServerThread;


/**
 *
 * @author bhlb
 */
public class MainView extends javax.swing.JFrame implements ShowMainViewInterface,ShowAdminMainViewInterface {
	
	private LoginPanel loginPanel;
	private ButtonsPanel buttonsPanel;
	private ItemInPanel itemInPanel;
	private ItemOutPanel itemOutPanel;
	private StoreAnalyPanel storeAnalyPanel;
    private VipManagePanel vipManagePanel;
    private GiftPanel giftPanel;
    private SynchroPanel synchroPanel;
    private AdminPanel adminPanel;
	private Thread server;

//	private StockPanel stockPanel;
    
	private void clear(){
		
	}
	

    /** Creates new form MainView */
    public MainView() {
    	loginPanel = new LoginPanel(this,this);
		buttonsPanel = new ButtonsPanel();
		itemInPanel = new ItemInPanel();
		itemOutPanel = new ItemOutPanel();
		storeAnalyPanel = new StoreAnalyPanel();
        vipManagePanel = new VipManagePanel();
        giftPanel = new GiftPanel();
        synchroPanel = new SynchroPanel();
        adminPanel = new AdminPanel();
		server = new ServerThread();
//		stockPanel = new StockPanel();
        
        initComponents();
    }
   
    @Override
	public void showMainView() {
		// TODO Auto-generated method stub
    	showVipManagePanel();
		
	}
    private void showItemInPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(itemInPanel);
    	pack();
    	repaint();
    }
    private void showItemOutPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(itemOutPanel);
    	pack();
    	repaint();
    }
    private void showStoreAnalyPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(storeAnalyPanel);
    	pack();
    	repaint();
    }
    private void showVipManagePanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(vipManagePanel);
    	pack();
    	repaint();
    }
    private void showGiftPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(giftPanel);
    	pack();
    	repaint();
    }
   
    
    private void showSynchroPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(buttonsPanel);
    	getContentPane().add(synchroPanel);
    	pack();
    	repaint();
    }
    private void showLoginView(){
    	getContentPane().add(loginPanel);
		pack();
    }
    public void showAdminPanel(){
    	getContentPane().removeAll();
    	getContentPane().add(adminPanel);
    	pack();
    	repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

//        buttonsPanel1 = new view.ButtonsPanel();
//        vipManagePanel1 = new view.VipManagePanel();
//        loginPanel = new LoginPanel(mainViewController);
        s = new GiftPanel();
//        setSize(1100, 700);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());
        showLoginView();

        pack();
    }// </editor-fold>

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    	Skin.set();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify

    private GiftPanel s;
    // End of variables declaration
    
    public class ButtonsPanel extends javax.swing.JPanel {

        /** Creates new form ButtonsPanel */
        public ButtonsPanel() {
            initComponents();
        }

        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            btn_synch = new javax.swing.JButton();
            btn_itemIn = new javax.swing.JButton();
            btn_itemOut = new javax.swing.JButton();
            btn_analy = new javax.swing.JButton();
            btn_vipManage = new javax.swing.JButton();
            btn_gift = new javax.swing.JButton();

            setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
            setPreferredSize(new java.awt.Dimension(149, 600));
            setLayout(null);

            btn_synch.setFont(getFont());
            btn_synch.setText("数据同步");
            btn_synch.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_synchActionPerformed(evt);
                }
            });
            add(btn_synch);
            btn_synch.setBounds(20, 470, 110, 40);

            btn_itemIn.setFont(getFont());
            btn_itemIn.setText("入库管理");
            btn_itemIn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_itemInActionPerformed(evt);
                }
            });
            add(btn_itemIn);
            btn_itemIn.setBounds(20, 20, 110, 40);

            btn_itemOut.setFont(getFont());
            btn_itemOut.setText("出库管理");
            btn_itemOut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_itemOutActionPerformed(evt);
                }
            });
            add(btn_itemOut);
            btn_itemOut.setBounds(20, 100, 110, 40);

            btn_analy.setFont(getFont());
            btn_analy.setText("库存分析");
            btn_analy.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_analyActionPerformed(evt);
                }
            });
            add(btn_analy);
            btn_analy.setBounds(20, 190, 110, 40);

            btn_vipManage.setFont(getFont());
            btn_vipManage.setText("会员管理");
            btn_vipManage.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_vipManageActionPerformed(evt);
                }
            });
            add(btn_vipManage);
            btn_vipManage.setBounds(20, 280, 110, 40);

            btn_gift.setFont(getFont());
            btn_gift.setText("礼品赠送");
            btn_gift.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_giftActionPerformed(evt);
                }
            });
            add(btn_gift);
            btn_gift.setBounds(20, 370, 110, 40);
        }// </editor-fold>

        private void btn_itemInActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        	showItemInPanel();
        }

        private void btn_itemOutActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        	showItemOutPanel();
        }

        private void btn_analyActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        	showStoreAnalyPanel();
        	System.out.println("dd");
        }

        private void btn_vipManageActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        	showVipManagePanel();
        }

        private void btn_giftActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        	showGiftPanel();
        }

        private void btn_synchActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        	showSynchroPanel();
        }


        // Variables declaration - do not modify
        private javax.swing.JButton btn_analy;
        private javax.swing.JButton btn_gift;
        private javax.swing.JButton btn_itemIn;
        private javax.swing.JButton btn_itemOut;
        private javax.swing.JButton btn_synch;
        private javax.swing.JButton btn_vipManage;
        // End of variables declaration

    }

	

}
