package view;

import javax.swing.JPanel;

public class SynchroPanel extends PanelModel {
	  public SynchroPanel() {
	        initComponents();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	     // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {
	
	        btn_down = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();
	        lab_ShopNum = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        text_down = new javax.swing.JTextArea();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        text_up = new javax.swing.JTextArea();
	        jScrollPane3 = new javax.swing.JScrollPane();
	        jTextArea3 = new javax.swing.JTextArea();
	
	        setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
	        setPreferredSize(new java.awt.Dimension(850, 630));
	        setLayout(null);
	
	        btn_down.setFont(getFont());
	        btn_down.setText("下载数据");
	        add(btn_down);
	        btn_down.setBounds(450, 110, 120, 30);
	
	        jButton3.setFont(getFont());
	        jButton3.setText("上传数据");
	        add(jButton3);
	        jButton3.setBounds(20, 110, 120, 30);
	
	        lab_ShopNum.setFont(getFont());
	        lab_ShopNum.setText("1");
	        add(lab_ShopNum);
	        lab_ShopNum.setBounds(720, 10, 30, 30);
	
	        jLabel2.setFont(getFont());
	        jLabel2.setText("店铺号");
	        add(jLabel2);
	        jLabel2.setBounds(630, 10, 90, 30);
	
	        text_down.setColumns(20);
	        text_down.setRows(5);
	        jScrollPane1.setViewportView(text_down);
	
	        add(jScrollPane1);
	        jScrollPane1.setBounds(590, 110, 250, 200);
	
	        text_up.setColumns(20);
	        text_up.setRows(5);
	        jScrollPane2.setViewportView(text_up);
	
	        add(jScrollPane2);
	        jScrollPane2.setBounds(160, 110, 250, 200);
	
	        jTextArea3.setColumns(20);
	        jTextArea3.setRows(5);
	        jScrollPane3.setViewportView(jTextArea3);
	
	        add(jScrollPane3);
	        jScrollPane3.setBounds(160, 110, 250, 200);
	    }// </editor-fold>
	
	
	    // Variables declaration - do not modify
	    private javax.swing.JButton btn_down;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JScrollPane jScrollPane3;
	    private javax.swing.JTextArea jTextArea3;
	    private javax.swing.JLabel lab_ShopNum;
	    private javax.swing.JTextArea text_down;
	    private javax.swing.JTextArea text_up;
	    // End of variables declaration
}
