/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GiftPanel.java
 *
 * Created on 2011-11-23, 23:59:47
 */

package view;

import java.util.ArrayList;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import logic.controller.ItemGiftController;
import logic.interfaces.ItemGiftInterface;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author bhlb
 */
public class ItemGiftPanel extends javax.swing.JPanel {

    /** Creates new form GiftPanel */
    public ItemGiftPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        removeAll();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_ID = new javax.swing.JTextField();
        text_giftID = new javax.swing.JTextField();
        text_giftIDInfo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_giftNo = new javax.swing.JTextField();
        text_beginDate = new javax.swing.JTextField();
        text_endDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_item = new javax.swing.JButton();
        btn_gift = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        text_removeID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setFont(new java.awt.Font("微软雅黑", 0, 18));
        setPreferredSize(new java.awt.Dimension(850, 630));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel1.setText("商品标识");
        add(jLabel1);
        jLabel1.setBounds(640, 140, 80, 30);

        jLabel2.setFont(getFont());
        jLabel2.setText("\u8d60\u54c1\u6807\u8bc6");
        add(jLabel2);
        jLabel2.setBounds(750, 140, 80, 30);
        add(text_ID);
        text_ID.setBounds(640, 180, 80, 30);
        add(text_giftID);
        text_giftID.setBounds(750, 180, 80, 30);
        add(text_giftIDInfo);
        text_giftIDInfo.setBounds(640, 60, 200, 75);

        jLabel3.setFont(getFont());
        jLabel3.setText("\u8d60\u54c1\u6570\u91cf");
        add(jLabel3);
        jLabel3.setBounds(640, 260, 80, 30);

        jLabel4.setFont(getFont());
        jLabel4.setText("开始日期");
        add(jLabel4);
        jLabel4.setBounds(640, 300, 80, 30);

        jLabel5.setFont(getFont());
        jLabel5.setText("结束日期");
        add(jLabel5);
        jLabel5.setBounds(640, 340, 80, 30);
        add(text_giftNo);
        text_giftNo.setBounds(750, 260, 80, 30);
        add(text_beginDate);
        text_beginDate.setBounds(750, 300, 80, 30);
        add(text_endDate);
        text_endDate.setBounds(750, 340, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "商品标识", "描述", "价格", "赠品标识", "描述", "价格", "开始时间", "结束时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(8).setResizable(false);

        add(jScrollPane1);
        jScrollPane1.setBounds(5, 60, 617, 494);

        jButton1.setFont(getFont());
        jButton1.setText("\u6dfb\u52a0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(640, 380, 80, 30);

        btn_item.setFont(getFont());
        btn_item.setText("确定");
        btn_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_itemActionPerformed(evt);
            }
        });
        add(btn_item);
        btn_item.setBounds(640, 220, 80, 30);

        btn_gift.setFont(getFont());
        btn_gift.setText("确定");
        btn_gift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giftActionPerformed(evt);
            }
        });
        add(btn_gift);
        btn_gift.setBounds(750, 220, 80, 30);

        jButton2.setFont(getFont());
        jButton2.setText("\u53d6\u6d88");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(750, 380, 80, 30);

        btn_remove.setFont(getFont());
        btn_remove.setText("移除");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        add(btn_remove);
        btn_remove.setBounds(750, 460, 80, 30);
        add(text_removeID);
        text_removeID.setBounds(750, 420, 80, 30);

        jLabel6.setFont(getFont());
        jLabel6.setText("\u4fc3\u9500\u6807\u8bc6");
        add(jLabel6);
        jLabel6.setBounds(640, 420, 80, 30);
        {
        	jLabel7 = new JLabel();
        	this.add(jLabel7);
        	jLabel7.setText("\u5546\u54c1\u8d60\u9001\u5217\u8868");
        	jLabel7.setBounds(5, 20, 150, 30);
        	jLabel7.setFont(new java.awt.Font("微软雅黑",0,18));
        }
        {
        	商品及赠品信息 = new JLabel();
        	this.add(商品及赠品信息);
        	商品及赠品信息.setText("\u5546\u54c1\u53ca\u8d60\u54c1\u4fe1\u606f");
        	商品及赠品信息.setBounds(640, 20, 150, 30);
        	商品及赠品信息.setFont(new java.awt.Font("微软雅黑",0,18));
        }

        controller=new ItemGiftController();
        controller.start();
        update();
        
    }// </editor-fold>

    
    
    
    public void update(){
		while(jTable1.getModel().getRowCount()!=0){
			((DefaultTableModel) jTable1.getModel()).removeRow(0);
		}
		ArrayList<String> promotions=controller.getPromotionList();
		if(promotions==null){
			return;
		}
		for(int i=0;i<promotions.size();i++){
			//System.out.println(itemListInfo.get(i));
			String item[]=promotions.get(i).split(",");
			((DefaultTableModel) jTable1.getModel()).addRow(item);
		}
    }
    private void btn_giftActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.setGiftID(text_giftID.getText());
    	if(!ok){
			JOptionPane.showMessageDialog(null, "输入错误");
			return;
    	}
    	text_giftIDInfo.setText(text_giftIDInfo.getText()+controller.getGiftInfo(text_giftID.getText()));
    }

    private void btn_itemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.setItemID(text_ID.getText());
    	if(!ok){
			JOptionPane.showMessageDialog(null, "输入错误");
			return;
    	}
    	text_giftIDInfo.setText(controller.getItemInfo(text_ID.getText()));
    }

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.removeGift(text_removeID.getText());
    	if(!ok){
			JOptionPane.showMessageDialog(null, "输入错误");
			return;
    	}
    	update();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	boolean ok=controller.setGift(text_giftNo.getText(), text_beginDate.getText(), text_endDate.getText());
    	if(!ok){
			JOptionPane.showMessageDialog(null, "输入错误");
			return;
    	}
    	update();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	initComponents();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btn_gift;
    private javax.swing.JButton btn_item;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private JLabel 商品及赠品信息;
    private JLabel jLabel7;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_ID;
    private javax.swing.JTextField text_beginDate;
    private javax.swing.JTextField text_endDate;
    private javax.swing.JTextField text_giftID;
    private javax.swing.JTextField text_giftIDInfo;
    private javax.swing.JTextField text_giftNo;
    private javax.swing.JTextField text_removeID;
    
    private ItemGiftInterface controller;
    // End of variables declaration

}
