/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GiftPanel.java
 *
 * Created on 2011-11-23, 23:59:47
 */

package view;

import javax.swing.table.DefaultTableModel;

//import Logic.GiftManageController;

/**
 *
 * @author bhlb
 */
public class GiftPanel extends PanelModel {
//商品列表部分未做
//	private GiftManageController gmc;
	
    /** Creates new form GiftPanel */
    public GiftPanel() {
//    	gmc = new GiftManageController(this, null);
        initComponents();
    }
    private void initializeSet() {
		
	}
	private void Update() {
		
	}
	private void reset() {
		
	}
	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
       // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_vipDealed = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_buyList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_itemList = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab_event = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_vipDeal = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab_VipInfo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_give = new javax.swing.JButton();
        text_date = new javax.swing.JTextField();
        text_num = new javax.swing.JTextField();
        btn_cancal = new javax.swing.JButton();
        rbtn_input = new javax.swing.JRadioButton();
        rbtn_select = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        text_itemID = new javax.swing.JTextField();

        setFont(new java.awt.Font("微软雅黑", 0, 18));
        setPreferredSize(new java.awt.Dimension(850, 630));
        setLayout(null);

        tab_vipDealed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "姓名"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_vipDealed);

        add(jScrollPane1);
        jScrollPane1.setBounds(680, 40, 150, 380);

        jLabel1.setFont(getFont());
        jLabel1.setText("赠送礼品列表");
        add(jLabel1);
        jLabel1.setBounds(20, 460, 130, 20);

        jLabel2.setFont(getFont());
        jLabel2.setText("待处理事件");
        add(jLabel2);
        jLabel2.setBounds(220, 10, 170, 20);

        tab_buyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "商品标识", "描述", "数量"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab_buyList);

        add(jScrollPane2);
        jScrollPane2.setBounds(200, 270, 440, 150);

        jLabel3.setFont(getFont());
        jLabel3.setText("赠送日期");
        add(jLabel3);
        jLabel3.setBounds(280, 550, 90, 30);

        tab_itemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "商品名", "价格"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tab_itemList);

        add(jScrollPane3);
        jScrollPane3.setBounds(20, 490, 240, 130);

        jLabel4.setFont(getFont());
        jLabel4.setText("已处理会员列表");
        add(jLabel4);
        jLabel4.setBounds(690, 10, 170, 20);

        tab_event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "生日赠送", "积分赠送", "完成情况"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tab_event);

        add(jScrollPane4);
        jScrollPane4.setBounds(210, 40, 390, 100);

        tab_vipDeal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "姓名"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tab_vipDeal);

        add(jScrollPane5);
        jScrollPane5.setBounds(10, 40, 160, 380);

        jLabel5.setFont(getFont());
        jLabel5.setText("需处理会员列表");
        add(jLabel5);
        jLabel5.setBounds(20, 10, 170, 20);

        jLabel6.setFont(getFont());
        jLabel6.setText("会员信息");
        add(jLabel6);
        jLabel6.setBounds(210, 150, 120, 20);

        lab_VipInfo.setText("jLabel7");
        add(lab_VipInfo);
        lab_VipInfo.setBounds(210, 170, 360, 60);

        jLabel8.setFont(getFont());
        jLabel8.setText("会员购买记录");
        add(jLabel8);
        jLabel8.setBounds(210, 240, 170, 20);

        jLabel9.setFont(getFont());
        jLabel9.setText("商品标识");
        add(jLabel9);
        jLabel9.setBounds(370, 440, 100, 20);

        btn_give.setFont(getFont());
        btn_give.setText("确认");
        btn_give.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giveActionPerformed(evt);
            }
        });
        add(btn_give);
        btn_give.setBounds(510, 490, 110, 100);

        text_date.setFont(getFont());
        text_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dateActionPerformed(evt);
            }
        });
        add(text_date);
        text_date.setBounds(380, 550, 120, 30);

        text_num.setFont(getFont());
        text_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_numActionPerformed(evt);
            }
        });
        add(text_num);
        text_num.setBounds(380, 490, 120, 30);

        btn_cancal.setFont(getFont());
        btn_cancal.setText("取消礼品赠送");
        btn_cancal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancalActionPerformed(evt);
            }
        });
        add(btn_cancal);
        btn_cancal.setBounds(660, 510, 180, 40);

        buttonGroup1.add(rbtn_input);
        rbtn_input.setText("输入赠送");
        rbtn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_inputActionPerformed(evt);
            }
        });
        add(rbtn_input);
        rbtn_input.setBounds(280, 440, 80, 23);

        buttonGroup1.add(rbtn_select);
        rbtn_select.setText("选择赠送");
        rbtn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_selectActionPerformed(evt);
            }
        });
        add(rbtn_select);
        rbtn_select.setBounds(180, 440, 103, 23);

        jLabel10.setFont(getFont());
        jLabel10.setText("赠送数量");
        add(jLabel10);
        jLabel10.setBounds(280, 490, 100, 20);
        add(text_itemID);
        text_itemID.setBounds(490, 440, 110, 30);
    }// </editor-fold>

    private void text_numActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void text_dateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_giveActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_cancalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rbtn_selectActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	if(rbtn_select.isSelected()){
  
    		text_itemID.setEditable(false);
    		
    	}
    }

    private void rbtn_inputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	if(rbtn_input.isSelected()){
//    		tab_itemList.setModel(null);
    		text_itemID.setEditable(true);
    		
    	}
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btn_cancal;
    private javax.swing.JButton btn_give;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lab_VipInfo;
    private javax.swing.JRadioButton rbtn_input;
    private javax.swing.JRadioButton rbtn_select;
    private javax.swing.JTable tab_buyList;
    private javax.swing.JTable tab_event;
    private javax.swing.JTable tab_itemList;
    private javax.swing.JTable tab_vipDeal;
    private javax.swing.JTable tab_vipDealed;
    private javax.swing.JTextField text_date;
    private javax.swing.JTextField text_itemID;
    private javax.swing.JTextField text_num;
    // End of variables declaration
	

}
