package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import logic.controller.ItemOutController;
import logic.interfaces.ItemOutInterface;

public class ItemOutPanel extends PanelModel{
	ItemOutInterface controller = new ItemOutController(); 
	 public ItemOutPanel() {
	        initComponents();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {

	        buttonGroup1 = new javax.swing.ButtonGroup();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        text_reason = new javax.swing.JTextField();
	        text_ID = new javax.swing.JTextField();
	        btn_ID = new javax.swing.JButton();
	        text_IDInfo = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jRadioButton4 = new javax.swing.JRadioButton();
	        jRadioButton1 = new javax.swing.JRadioButton();
	        jRadioButton2 = new javax.swing.JRadioButton();
	        jRadioButton3 = new javax.swing.JRadioButton();
	        text_Num = new javax.swing.JTextField();
	        btn_Close = new javax.swing.JButton();
	        btn_Out = new javax.swing.JButton();
	        btn_Open = new javax.swing.JButton();

	        setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
	        setPreferredSize(new java.awt.Dimension(850, 630));
	        setLayout(null);

	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "商品标识", "描述", "价格", "报废数量"
	            }
	        ) {
	            Class[] types = new Class [] {
	                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
	            };
	            boolean[] canEdit = new boolean [] {
	                false, false, true, false
	            };

	            public Class getColumnClass(int columnIndex) {
	                return types [columnIndex];
	            }

	            public boolean isCellEditable(int rowIndex, int columnIndex) {
	                return canEdit [columnIndex];
	            }
	        });
	        jScrollPane1.setViewportView(jTable1);

	        add(jScrollPane1);
	        jScrollPane1.setBounds(22, 42, 480, 530);

	        jLabel1.setFont(getFont());
	        jLabel1.setText("商品信息");
	        add(jLabel1);
	        jLabel1.setBounds(510, 80, 100, 40);

	        jLabel2.setFont(getFont());
	        jLabel2.setText("下架原因");
	        add(jLabel2);
	        jLabel2.setBounds(520, 300, 90, 30);

	        text_reason.setFont(getFont());
	        text_reason.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                text_reasonActionPerformed(evt);
	            }
	        });
	        add(text_reason);
	        text_reason.setBounds(640, 300, 140, 30);

	        text_ID.setFont(getFont());
	        add(text_ID);
	        text_ID.setBounds(640, 30, 110, 30);

	        btn_ID.setFont(getFont());
	        btn_ID.setText("确定");
	        btn_ID.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_IDActionPerformed(evt);
	            }
	        });
	        add(btn_ID);
	        btn_ID.setBounds(760, 30, 80, 30);
	        add(text_IDInfo);
	        text_IDInfo.setBounds(610, 90, 230, 140);

	        jLabel3.setFont(getFont());
	        jLabel3.setText("输入商品标识");
	        add(jLabel3);
	        jLabel3.setBounds(510, 30, 120, 30);

	        jLabel4.setFont(getFont());
	        jLabel4.setText("商品数量");
	        add(jLabel4);
	        jLabel4.setBounds(520, 250, 90, 30);

	        buttonGroup1.add(jRadioButton4);
	        jRadioButton4.setText("批次质量缺陷");
	        add(jRadioButton4);
	        jRadioButton4.setBounds(650, 380, 130, 23);

	        buttonGroup1.add(jRadioButton1);
	        jRadioButton1.setText("转移到其他店铺");
	        add(jRadioButton1);
	        jRadioButton1.setBounds(520, 340, 130, 23);

	        buttonGroup1.add(jRadioButton2);
	        jRadioButton2.setText("到期报废");
	        add(jRadioButton2);
	        jRadioButton2.setBounds(650, 340, 130, 23);

	        buttonGroup1.add(jRadioButton3);
	        jRadioButton3.setText("个别残次品");
	        add(jRadioButton3);
	        jRadioButton3.setBounds(520, 380, 130, 23);

	        text_Num.setFont(getFont());
	        add(text_Num);
	        text_Num.setBounds(640, 250, 140, 30);

	        btn_Close.setFont(getFont());
	        btn_Close.setText("结束出库");
	        btn_Close.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_CloseActionPerformed(evt);
	            }
	        });
	        add(btn_Close);
	        btn_Close.setBounds(690, 500, 130, 40);

	        btn_Out.setFont(getFont());
	        btn_Out.setText("出库");
	        btn_Out.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_OutActionPerformed(evt);
	            }
	        });
	        add(btn_Out);
	        btn_Out.setBounds(600, 420, 130, 40);

	        btn_Open.setFont(getFont());
	        btn_Open.setText("开始出库");
	        btn_Open.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btn_OpenActionPerformed(evt);
	            }
	        });
	        add(btn_Open);
	        btn_Open.setBounds(530, 500, 130, 40);
	        initializeSet();
	    }// </editor-fold>

	  //更新显示信息 
		private void Update(){
			
		}
		//初始化默认设置
		private void initializeSet() {
			text_ID.setEditable(false);
			text_IDInfo.setEditable(false);
			text_Num.setEditable(false);
			text_reason.setEditable(false);
			text_ID.setText("");
			text_IDInfo.setText("");
			text_Num.setText("");
			text_reason.setText("");
			jTable1.setModel(new javax.swing.table.DefaultTableModel(
		            new Object [][] {
		               
		            },
		            new String [] {
		                "商品标识", "描述", "价格", "报废数量", "报废原因"
		            }
		        ) {
		            Class[] types = new Class [] {
		                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
		            };
		            boolean[] canEdit = new boolean [] {
		                false, false, false, true, true
		            };

		            public Class getColumnClass(int columnIndex) {
		                return types [columnIndex];
		            }

		            public boolean isCellEditable(int rowIndex, int columnIndex) {
		                return canEdit [columnIndex];
		            }
		        });
//			jRadioButton1.set
			
			
			
			
		}
		//重置设置
		private void reset() {
			text_ID.setEditable(false);
			text_IDInfo.setEditable(false);
			text_Num.setEditable(false);
			text_reason.setEditable(false);
			text_ID.setText("");
			text_IDInfo.setText("");
			text_Num.setText("");
			text_reason.setText("");
			jTable1.setModel(new javax.swing.table.DefaultTableModel(
		            new Object [][] {
		                
		            },
		            new String [] {
		                "商品标识", "描述", "价格", "报废数量", "报废原因"
		            }
		        ) {
		            Class[] types = new Class [] {
		                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
		            };
		            boolean[] canEdit = new boolean [] {
		                false, false, false, true, true
		            };

		            public Class getColumnClass(int columnIndex) {
		                return types [columnIndex];
		            }

		            public boolean isCellEditable(int rowIndex, int columnIndex) {
		                return canEdit [columnIndex];
		            }
		        });
			
		}
	    
	    private void text_reasonActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    }

	    private void btn_IDActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    	if(!text_ID.isEditable()){
	    		JOptionPane.showMessageDialog(null, "请先点击开始出库");
	    		return;
	    	}
	    	try{
				Integer.parseInt(text_ID.getText());
			}catch(NumberFormatException e){
				JOptionPane.showMessageDialog(null, "格式错误");
	    		return;
				
			}
			text_ID.setEditable(false);
	    	String temp = controller.getStockItemInfoByID(text_ID.getText());
	    	if(temp==null){
	    		JOptionPane.showMessageDialog(null, "库存中没有此商品");
	    		text_ID.setEditable(true);
	    		text_IDInfo.setEditable(false);
				text_Num.setEditable(false);
				text_reason.setEditable(false);
	    	}else{
	    		text_IDInfo.setText(temp);
	    		text_IDInfo.setEditable(false);
				text_Num.setEditable(true);
				text_reason.setEditable(true);
	    	}
	    }

	    private void btn_OutActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    	
	    	if(!text_Num.isEditable()){
	    		JOptionPane.showMessageDialog(null, "请先点击开始入库");
	    		return;
	    	}
	    	int tempNum=0;
	    	String tempReason =null;
	    	
	    	try{
	    		tempNum = Integer.parseInt(text_Num.getText());
			}catch(NumberFormatException e){
				JOptionPane.showMessageDialog(null, "数量格式有错！");
				return;
			}
			if(jRadioButton1.isSelected()){
				tempReason = "转移到其他店铺";
			}else if(jRadioButton2.isSelected()){
				tempReason = "到期报废";
			}else if(jRadioButton3.isSelected()){
				tempReason = "个别残次品";
			}else if(jRadioButton4.isSelected()){
				tempReason = "批次质量缺陷";
			}
			if(!text_reason.getText().equals("")){
				tempReason = text_reason.getText();
			}
			
			String [] temp = controller.getStockItemInfoByID(text_ID.getText()).split(",");
			int column = jTable1.getColumnCount();
			Object[] newRow = {text_ID.getText(),temp[1],Double.parseDouble(temp[2]),tempNum,tempReason};
			((DefaultTableModel)jTable1.getModel()).addRow(newRow);
//			String []
			text_ID.setEditable(true);
			text_IDInfo.setEditable(false);
			text_Num.setEditable(false);
			text_reason.setEditable(false);
			text_ID.setText("");
			text_IDInfo.setText("");
			text_Num.setText("");
			text_reason.setText("");
			
			
			
	    }

	    private void btn_OpenActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    	text_ID.setEditable(true);
	    	
	    }

	    private void btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {
	        // TODO add your handling code here:
	    	if((!text_Num.isEditable())&&(!text_ID.isEditable())){
	    		JOptionPane.showMessageDialog(null, "请先点击开始出库");
	    		return;
	    	}
	    	String [] s =new String[jTable1.getRowCount()];
	    	String temp = null;
	    	for(int i=0;i<s.length;i++){
	    		temp = (String) jTable1.getModel().getValueAt(i, 0)+","+(String)jTable1.getModel().getValueAt(i, 1)
	    		+","+((Double)jTable1.getModel().getValueAt(i, 2)).toString()+","+
	    		((Integer) jTable1.getModel().getValueAt(i, 3)).toString()+","
	    			+(String)jTable1.getModel().getValueAt(i, 4);
	    		s[i]=temp;
	    	}
	    	controller.writeStockData(s);
	    	reset();
	    }


	    // Variables declaration - do not modify
	    private javax.swing.JButton btn_Close;
	    private javax.swing.JButton btn_ID;
	    private javax.swing.JButton btn_Open;
	    private javax.swing.JButton btn_Out;
	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JRadioButton jRadioButton4;
	    private javax.swing.JRadioButton jRadioButton1;
	    private javax.swing.JRadioButton jRadioButton2;
	    private javax.swing.JRadioButton jRadioButton3;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTable jTable1;
	    private javax.swing.JTextField text_ID;
	    private javax.swing.JTextField text_IDInfo;
	    private javax.swing.JTextField text_Num;
	    private javax.swing.JTextField text_reason;
	    // End of variables declaration

}
