package view;

import javax.swing.JOptionPane;

import logic.controller.GoodsManageController;
import logic.interfaces.GoodsManageInterface;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageItemPanel.java
 *
 * Created on 2011-11-26, 15:12:42
 */



/**
 *
 * @author bhlb
 */
public class ManageItemPanel extends PanelModel{

	private GoodsManageInterface controller = new GoodsManageController();
    /** Creates new form ManageItemPanel */
    public ManageItemPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_ID1 = new javax.swing.JTextField();
        text_ID = new javax.swing.JTextField();
        text_name = new javax.swing.JTextField();
        btn_addSure = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        text_price = new javax.swing.JTextField();
        btn_deleteSure = new javax.swing.JButton();

        setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 630));
        setRequestFocusEnabled(false);
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "商品标识", "商品描述", "商品价格"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 410, 570);

        btn_add.setFont(jLabel1.getFont());
        btn_add.setText("添加商品");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        add(btn_add);
        btn_add.setBounds(480, 30, 150, 50);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel1.setText("商品标识");
        add(jLabel1);
        jLabel1.setBounds(490, 450, 120, 50);

        jLabel2.setFont(jLabel1.getFont());
        jLabel2.setText("商品描述");
        add(jLabel2);
        jLabel2.setBounds(480, 170, 100, 40);

        jLabel3.setFont(jLabel1.getFont());
        jLabel3.setText("商品价格");
        add(jLabel3);
        jLabel3.setBounds(480, 230, 100, 50);
        add(text_ID1);
        text_ID1.setBounds(630, 460, 130, 40);
        add(text_ID);
        text_ID.setBounds(640, 100, 130, 40);
        add(text_name);
        text_name.setBounds(640, 170, 130, 40);

        btn_addSure.setFont(btn_add.getFont());
        btn_addSure.setText("添加");
        btn_addSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSureActionPerformed(evt);
            }
        });
        add(btn_addSure);
        btn_addSure.setBounds(580, 310, 130, 40);

        btn_close.setFont(jLabel1.getFont());
        btn_close.setText("关闭添加");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        add(btn_close);
        btn_close.setBounds(680, 30, 150, 50);

        btn_delete.setFont(btn_add.getFont());
        btn_delete.setText("删除商品");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        add(btn_delete);
        btn_delete.setBounds(480, 380, 140, 50);

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 24));
        jLabel4.setText("商品标识");
        add(jLabel4);
        jLabel4.setBounds(480, 90, 120, 50);
        add(text_price);
        text_price.setBounds(640, 240, 130, 40);

        btn_deleteSure.setFont(btn_add.getFont());
        btn_deleteSure.setText("删除");
        btn_deleteSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSureActionPerformed(evt);
            }
        });
        add(btn_deleteSure);
        btn_deleteSure.setBounds(580, 520, 130, 40);
        initializeSet() ;
    }// </editor-fold>

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	text_ID.setEditable(true);
    	text_name.setEditable(true);
    	text_price.setEditable(true);
    	text_ID1.setEditable(false);
    	text_ID1.setText("");
    	text_price.setText("");
    	text_name.setText("");
    	
    }                                       

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	text_ID.setEditable(false);
    	text_name.setEditable(false);
    	text_price.setEditable(false);
    	text_ID1.setEditable(false);
    	text_ID.setText("");
    	text_price.setText("");
    	text_name.setText("");
    	
    }                                         

    private void btn_addSureActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	String temp = text_ID.getText()+","+text_name.getText()+","+text_price.getText();
    	Boolean check = controller.checkInputID(text_ID.getText())&&controller.checkInputPrice(text_price.getText());
    	if(check){
    		Boolean success = controller.addData(temp);
    		if(success){
    			Update();
    		}else{
    			JOptionPane.showMessageDialog(null, "该商品已存在");
    		}
    		
    	}else{
    		JOptionPane.showMessageDialog(null, "格式错误");
    	}
    	text_ID.setText("");
    	text_price.setText("");
    	text_name.setText("");
    	
    }                                           

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	text_ID.setEditable(false);
    	text_name.setEditable(false);
    	text_price.setEditable(false);
    	text_ID1.setEditable(true);
    	text_ID1.setText("");
    }                                          

    private void btn_deleteSureActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	Boolean check = controller.checkInputID(text_ID1.getText());
    	Boolean success = false;
    	if(check){
    		success = controller.deleteData(text_ID1.getText());
    		if(success){
    			Update();
    		}else{
    			JOptionPane.showMessageDialog(null, "不存在此商品");
    		}
    	}else{
    		JOptionPane.showMessageDialog(null, "ID格式错误");
    	}
    	text_ID1.setText("");
    	text_ID1.setEditable(true);
    }                                              

  //更新显示信息 
	private void Update(){
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
                controller.getTable(),
                    new String [] {
                        "商品标识", "商品描述", "商品价格"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
	}
	//初始化默认设置
	private void initializeSet() {
		text_ID.setEditable(false);
    	text_name.setEditable(false);
    	text_price.setEditable(false);
    	text_ID1.setEditable(false);
    	jTable1.setModel(new javax.swing.table.DefaultTableModel(
                controller.getTable(),
                    new String [] {
                        "商品标识", "商品描述", "商品价格"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                        false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
	}
	//重置设置
	private void reset() {
		
	}

    // Variables declaration - do not modify
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addSure;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleteSure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_ID;
    private javax.swing.JTextField text_ID1;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextField text_price;
	
    // End of variables declaration

	

}
